# Generated by Django 3.2.4 on 2021-07-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShipData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('imoNumber', models.CharField(max_length=60)),
                ('start_date', models.CharField(max_length=160)),
                ('latitude', models.CharField(max_length=160)),
                ('longitude', models.CharField(max_length=160)),
            ],
        ),
    ]
