# Generated by Django 3.2.4 on 2021-07-02 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pole_app', '0002_rename_start_date_shipdata_time_stamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipdata',
            options={'ordering': ('name',)},
        ),
    ]
